### ISSUE TITLE
npm package version 1.0.3 doesn't include upsertRecord

### ISSUE THREAD

**Issue by umairda** [chilts/nice-route53#16]
npm package version 1.0.3 (latest) doesn't include upsertRecord

**Comment by leorossi** [comment]
I have update the package on npm registry.
@chilts can you please have a look that everything is ok? Thanks!

**Comment by chilts** [comment]
I can see the 1.0.4 package on npm.

When I install it locally, I can see the following line in the file:

```
Route53.prototype.upsertRecord = function(opts, pollEvery, callback) {
```

Am I late in looking and that wasn't in 1.0.3 but it is in 1.0.4? Anyway, from what I can see it looks like it's there. :)

**Comment by leorossi** [comment]
Ok, so @umairda install version 1.0.4 to be sure to have `upsertRecord`

**Comment by chilts** [comment]
Thanks @leorossi ... again, I very much appreciate your involvement in nice-route53. :)
