### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by hgezim** [chilts/nice-route53#22]
Hi,

Is this still being maintained? I see issues from 2016 and a PR from 2014.

**Comment by leorossi** [comment]
Hi!

I was using this library in 2015/2016 and started contributing to it but I am not maintaining actively this repo anymore.

**Comment by chilts** [comment]
I don't actively use AWS anymore, but I can always look at or review anything you want to point out specifically? ie. I dunno if the PR from 2014 or issues are either still relevant or wanted. Apologies.

**Comment by chilts** [comment]
I might just archive this package and repo. Anyone any objections?

**Comment by leorossi** [comment]
I suggest to put on the readme this package is not maintained anymore.

**Comment by hgezim** [comment]
I'm finding the code useful, actually and others might as well. So probably a readme update suffices.

**Comment by chilts** [comment]
Ah yep, good call. I'll add something to the readme and do a new release so it's also on npm.

**Comment by chilts** [comment]
I've added a PR here : https://github.com/chilts/nice-route53/pull/23 (apologies for the 2 unrelated commits). I'll merge and re-release shortly unless either of you have any further suggestions/fixes/notes. :) Many thanks for your help and input.
