### ISSUE TITLE
setRecord error

### ISSUE THREAD

**Issue by jamesyoung** [chilts/nice-route53#8]
When trying to setRecord or delRecord, I get the following error : 

{ type: 'InvalidInput',
  code: 400,
  msg: 'Invalid XML ; cvc-complex-type.2.4.b: The content of element \'ResourceRecords\' is not complete. One of \'{"https://route53.amazonaws.com/doc/2013-04-01/":ResourceRecord}\' is expected.' }

I followed along with the README.md example. Here is my args : 

var args = {
    zoneId : '<my zoneid retrieved from doing a records call first>',
    name   : 'test.mydomain.com',
    type   : 'A',
    ttl    : 600,
    values : [
        '127.0.0.1',
    ],
};

I do not know what I am missing from ResourceRecords. Any help would be greatly appreciated.

**Comment by chilts** [comment]
The only thing I can see there is that you have an empty `zoneId` - though I guess you just removed that for copying here. I dunno. I'm not really maintaining this anymore.

**Comment by leorossi** [comment]
You are missing the `zoneId` field, that's why you get that error.

**Comment by jamesyoung** [comment]
thanks!
